ALTER TYPE "DigitalTier" ADD VALUE IF NOT EXISTS 'HD_6X';
ALTER TYPE "DigitalTier" ADD VALUE IF NOT EXISTS 'HD_8X';
ALTER TYPE "DigitalTier" ADD VALUE IF NOT EXISTS 'HD_10X';
ALTER TYPE "DigitalTier" ADD VALUE IF NOT EXISTS 'HD_12X';
